services:
  drogon:
    image: drogonframework/drogon
    container_name: drogon_app
    ports:
      - "6543:6543"
      - "9876:9876"
      - "8080:80"
    volumes:
      - ./drogon_app:/app
      - ./db:/db
    working_dir: /app
      #command: tail -f /dev/null
    command: >
      bash -c "
      rm -rf ./build/* &&
      mkdir -p build &&
      cd build &&
      cmake .. &&
      make &&
       ./drogon_app"
    depends_on:
      - sqlite

  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./db:/db
    working_dir: /db
    stdin_open: true
    tty: true

